spring:
  datasource:
#    url: jdbc:h2:mem:maindb
    url: jdbc:postgresql://MACBOOKAIR-5AB2:5432/db_docker
#    url: jdbc:postgresql://localhost:5432/db_docker
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true

  output:
    ansi:
      enabled: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  data:
    rest:
      basePath: /datarest

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,logfile,prometheus"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  jmx:
    enabled: true

logging:
  level:
    ROOT: DEBUG
  file:
    name: ./logs/hw16-actuator.log