services:
  document-store-service:
    build:
      context: .
      dockerfile: document-store-service.Dockerfile
    ports:
      - "8080:8080"

  document-printer-service:
    build:
      context: .
      dockerfile: document-printer-service.Dockerfile
    ports:
      - "8081:8081"

  document-maker-service:
    build:
      context: .
      dockerfile: document-maker-service.Dockerfile
    ports:
      - "8082:8082"

  auth-gateway-service:
    build:
      context: .
      dockerfile: auth-gateway-service.Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/db_docker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    image: "postgres:17"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_docker