server:
  port: 8083
  max-http-request-header-size: 2048KB

document-maker-service:
  url: http://localhost:8082

spring:
  application:
    name: security-security
  output:
    ansi:
      enabled: always
#  datasource:
#    url: jdbc:postgresql://ALEXANDERS-AIR:5432/db_auth
#    #    url: jdbc:postgresql://localhost:5432/db_docker
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
#    url: jdbc:h2:mem:security-security
#    driverClassName: org.h2.Driver
#    username: root
#    password: root
  datasource:
    url: jdbc:postgresql://ALEXANDERS-AIR:5432/db_docker
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10000
        failureRateThreshold: 60
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
    instances:
      document-maker-service:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,logfile,prometheus"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  jmx:
    enabled: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855